import 'dart:ui';

import 'package:flutter/material.dart';

class MColors {
  static const red =  Colors.red;
  static const blue = Colors.blueAccent;
  static const tomato = const Color(0xfff43630);
  static const warm_grey = const Color(0xff999696);
  static const warm_grey08 = Color.fromRGBO(153, 150, 150, 0.8);
  static const white_two = const Color(0xfff4f4f4);
  static const white_two08 = const Color.fromRGBO(244, 244, 244, 0.8);
  static const whiteColor = Color.fromRGBO(254, 254, 254, 1.0);
  static const white23 = Color.fromRGBO(255, 255, 255, 0.23);
  static const azul = const Color(0xff2f74d5);
  static const darkish_blue = const Color(0xff03318c);
  static const pale_salmon = const Color(0xffff9e9e);
  static const deep_lilac = const Color(0xff8a68ca);
  static const jungle_green = const Color(0xff038c60);
  static const tan_green = const Color(0xffacca68);
  static const purple_red = const Color(0xff8c034d);
  static const pinkish_grey = const Color(0xffb9b6b6);
  static const pinkishGrey10 = Color.fromRGBO(185, 182, 182, 0.1);
  static const grey_06 = const Color(0xff383535);
  static const grey_05 = const Color(0xff666060);
  static const golden_rod = const Color(0xffeebb14);
  static const white_three = const Color(0xffdbdbdb);
  static const white_three08 = const Color(0xccdbdbdb);
  static const black = const Color(0xff000000);
  static const faded_orange = const Color(0xffe7a34b);
  static const cobalt = const Color(0xff1c5b8a);
  static const viridian = const Color(0xff1c8a6a);
  static const dusty_orange = const Color(0xffff6f2d);
  static const blackColor = const Color(0xff080606);
  static const white = const Color(0xfffefefe);
  static const greyish = const Color(0xffb8b8b8);
  static const greyish_brown = const Color(0xff434343);
  static const brownish_pink = const Color(0xffb38d80);
  static const grapefruit = const Color(0xffff5252);
  static const very_light_pink = const Color(0xfff1f1f1);
  static const kakao_yellow = const Color(0xfffbe100);
  static const kakao_brown = const Color(0xff392020);
  static const naver_green = const Color(0xff2cb400);
  static const facebook_blue = const Color(0xff0079fc);
  static const black36 = const Color(0xff242424);
  static const black40 = const Color(0x66000000);
  static const brownish_grey = const Color(0xff6a6a6a);
  static const brown_grey = const Color(0xff7a7a7a);
  static const tomato_10 = const Color(0x1ae73331);
  static const tomato_20 = const Color(0x33e73331);
  static const pinkBack = const Color(0xfffef9f9);
  static const black_three = const Color(0xff161616);
  static const white_four = const Color(0xfff8f8f8);
  static const salmon = const Color(0xfff87474);
  static const barBackgroundColor = white_two;
  static const backgroundColor_white = const Color(0xfffcfcfc);
  static const barBorderColor = white_three;
  static const onBoardingColorStart = const Color.fromRGBO(225, 221 , 210, 1.0);
  static const onBoardingColorEnd = const Color.fromRGBO(204, 194 , 173, 1.0);
  static const snackBarColor = const Color.fromRGBO(0,0,0, 0.8);
  static const defaultButtonColor = const Color.fromRGBO(255, 82, 82, 1.0);
  static const gradientBlurColorStartWhite = const Color(0x00ffffff);
  static const gradientBlurColorEndWhite = const Color(0xfffcfcfc);
}

const barBorderWidth = 0.5;
